export enum EIconName {
  Search = 'Search',
  Phone = 'Phone',
  CloseSquare = 'CloseSquare',
  Eye = 'Eye',
  CaretDown = 'CaretDown',
  Calendar = 'Calendar',
  AngleLeft = 'AngleLeft',
  AngleRight = 'AngleRight',
  Check = 'Check',
  Copy = 'Copy',
  Info = 'Info',
  Camera = 'Camera',
  Play = 'Play',
  Locker = 'Locker',
  Pause = 'Pause',
  Saved = 'Saved',
  Unsaved = 'Unsaved',
  Menu = 'Menu',
  Prev = 'Prev',
  Next = 'Next',
  TimePastPrev = 'TimePastPrev',
  TimePastNext = 'TimePastNext',
}

export enum EIconColor {
  BLACK = '#000',
  WHITE = '#fff',
  NOBEL = '#B8B6B6',
  ORANGE_PEEL = '#FF9F00',
  SILVER = '#c4c4c4',
  GREEN_HAZE = '#01A358',
  SCORPION = '#5F5E5E',
}
