export enum EKeyStateModalAuth {
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  VERIFY_OTP_FORGOT = 'VERIFY_OTP_FORGOT',
  VERIFY_OTP_REGISTER = 'VERIFY_OTP_REGISTER',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
}
