export enum EUIAction {
  SET_DEVICE = 'SET_DEVICE',
  TOGGLE_MODAL_AUTH = 'TOGGLE_MODAL_AUTH',
  RESET_ACTION_STATUS = 'RESET_ACTION_STATUS',
  SET_AUDIO = 'SET_AUDIO',
  SET_CATEGOIRES = 'SET_CATEGOIRES',
  SET_MOODS_REASONS = 'SET_MOODS_REASONS',
}
